### ISSUE TITLE
Don't work in Webpack: 5.74.0

### ISSUE THREAD

**Issue by dlnsk** [ubilabs/webpack-node-modules-list#16]
webpack: 5.74.0
webpack-cli: 4.10.0
webpack-dev-server 4.11.1

[webpack-cli] TypeError: compiler.plugin is not a function
    at ExportNodeModules.apply (/node_modules/webpack-node-modules-list/index.js:15:12)
